### ISSUE TITLE
Use string.gsub and utf8 to remove illegal ZWJ characters

### ISSUE THREAD

**Issue by FilteredDev** [va1kio/roblox-assets#1]
Many scam bots can get around your filter using large amounts of zero-width characters. A human cannot see this, but a filter can.

If you combine gsub with utf8, you can remove these characters
```lua
local str = "Hello World!"
print(str:gsub("l", "") -->Heo Word!
```

**Comment by va1kio** [comment]
Solved, check commit `b210695`
